### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by KOT040188** [sr-tream/qsudo#3]
kot@kot-MS-7930:~/qsudo/build$ make
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../qsudo.ui -o ui_qsudo.h
make: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not found
Makefile:206: recipe for target 'ui_qsudo.h' failed
make: *** [ui_qsudo.h] Error 127

**Comment by sr-tream** [comment]
qt5 нужен, а не qt4

**Comment by KOT040188** [comment]
Оно само потребовало qt4
kot@kot-MS-7930:~/qsudo/build$ qmake ..
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

**Comment by sr-tream** [comment]
Попробуйте тогда qmake-qt5 использовать вместо qmake

**Comment by KOT040188** [comment]
Не понял что делать. У меня стоят qt4-qmake и qt5-qmake.

**Comment by KOT040188** [comment]
Так что ли?
kot@kot-MS-7930:~/qsudo/build$ qmake-qt5 ..

Command 'qmake-qt5' not found, did you mean:

  command 'qmake-qt4' from deb qt4-qmake

Try: sudo apt install <deb name>

**Comment by sr-tream** [comment]
Какой дистрибутив?

**Comment by KOT040188** [comment]
Kubuntu 18.04

**Comment by sr-tream** [comment]
sudo apt install qt5-default
Должно поставить все необходимое для сборки софта с qt5

**Comment by KOT040188** [comment]
Всё равно
kot@kot-MS-7930:~/qsudo/build$ qmake-qt5 ..

Command 'qmake-qt5' not found, did you mean:

  command 'qmake-qt4' from deb qt4-qmake

Try: sudo apt install <deb name>

**Comment by sr-tream** [comment]
А так?
/usr/lib/qt5/bin/qmake

**Comment by KOT040188** [comment]
kot@kot-MS-7930:~/qsudo/build$ /usr/lib/qt5/bin/qmake ..
Info: creating stash file /home/kot/qsudo/build/.qmake.stash

**Comment by sr-tream** [comment]
ну и? make после этого нормально собирает?

**Comment by KOT040188** [comment]
kot@kot-MS-7930:~/qsudo/build$ make
/usr/lib/qt5/bin/uic ../qsudo.ui -o ui_qsudo.h
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../qsudo -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o ../main.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../qsudo -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o qsudo.o ../qsudo.cpp
/usr/lib/qt5/bin/rcc -name res ../res.qrc -o qrc_res.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../qsudo -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o qrc_res.o qrc_res.cpp
g++ -pipe -std=c++11 -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
/usr/lib/qt5/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kot/qsudo -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../qsudo.h -o moc_qsudo.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../qsudo -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_qsudo.o moc_qsudo.cpp
g++ -Wl,-O1 -o qsudo main.o qsudo.o qrc_res.o moc_qsudo.o   -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread

**Comment by sr-tream** [comment]
Ну, вроде все нормально. Теперь должен быть файл qsudo в папке build

**Comment by KOT040188** [comment]
Есть.

**Comment by sr-tream** [comment]
Ну все, это и есть программа

**Comment by KOT040188** [comment]
Я понял.

**Comment by KOT040188** [comment]
Хотел дебку собрать. Но в ней почему-то бинарника нет…

kot@kot-MS-7930:~/qsudo/build$ sudo checkinstall --install=no

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
         Эта программа распространяется на условиях GNU GPL


The package documentation directory ./doc-pak does not exist. 
Should I create a default set of package docs?  [y]: 

Готовится документация к пакету...OK

*** No known documentation files were found. The new package 
*** won't include a documentation directory.

*****************************************
**** Debian package creation selected ***
*****************************************

Этот пакет был создан с использованием данных значений: 

0 -  Maintainer: [ root@kot-MS-7930 ]
1 -  Summary: [ Qsudo. GUI for sudo. ]
2 -  Name:    [ qsudo ]
3 -  Version: [ 20180527 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ build ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ build ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Введите номер для изменения параметра или нажмите ВВОД для продолжения: 

Installing with make install...

========================= Результаты установки ===========================
make: Цель «install» не требует выполнения команд.

======================== Установка успешно завершена ======================
cp: не удалось выполнить stat для '//var/tmp/tmp.lv6puLRA0R/newfiles.tmp': Нет такого файла или каталога

Файлы копируются во временный каталог...OK

Stripping ELF binaries and libraries...OK

Сжимаются страницы руководства...OK

Построение списка файлов... FAILED!

Собирается Debian-пакет...OK

ЗАМЕТКА: Пакет не установлен

Удаляются временные файлы...OK

Удаляется временный каталог...OK


**********************************************************************

 Done. The new package has been saved to

 /home/kot/qsudo/build/qsudo_20180527-1_amd64.deb
 You can install it in your system anytime using: 

      dpkg -i qsudo_20180527-1_amd64.deb

**********************************************************************

**Comment by sr-tream** [comment]
Ну в построении файлов ошибка. Я хз в чем проблема с твоей тулзой, я только в ручную пакеты собирал.
